#!/bin/bash

# Function to check if Docker is installed
check_docker() {
    if ! command -v docker &> /dev/null; then
        echo "Docker is not installed. Please install Docker and try again."
        exit 1
    fi
}

# Function to ensure the fcm container is running
ensure_fcm_running() {
    if ! docker ps --format '{{.Names}}' | grep -q '^fcm$'; then
        echo "fcm container is not running. Starting it..."
        docker stop fcm >/dev/null 2>&1 || true
        docker container rm fcm >/dev/null 2>&1 || true
        docker run --name fcm -d --restart=unless-stopped -v /var/run/docker.sock:/var/run/docker.sock registry.gitlab.com/fatchilli/devops/fcm/fcm:latest
    fi
}

# The main command handler
function main() {
    case "$1" in
        restart)
            check_docker
            docker stop fcm >/dev/null 2>&1 || true
            docker container rm fcm >/dev/null 2>&1 || true
            docker image rm registry.gitlab.com/fatchilli/devops/fcm/fcm:latest >/dev/null 2>&1 || true
            docker run --name fcm -d --restart=unless-stopped -v /var/run/docker.sock:/var/run/docker.sock registry.gitlab.com/fatchilli/devops/fcm/fcm:latest
            ;;
        remp-list)
            check_docker
            ensure_fcm_running
            docker exec -i fcm remp-list
            ;;
        remp-install)
            check_docker
            ensure_fcm_running
            shift # Shift the arguments to skip the first one (remp-install)
            docker exec -i fcm remp-install "$@"
            ;;
        --version|-v)
            echo "v0.1.7"
            ;;
        *)
            echo "Unknown command: $1"
            exit 1
            ;;
    esac
}

# Check if at least one argument is provided
if [ $# -lt 1 ]; then
    echo "Usage: fcm <command> [arguments]"
    echo "Commands:"
    echo "  restart        Re-installs the docker container"
    echo "  remp-list      List REMPs"
    echo "  remp-install   Install a REMP"
    echo "  --version, -v  Display the version of the script"
    exit 1
fi

# Run the main function with all script arguments
main "$@"