#!/bin/bash

# Function to check if Docker is installed
check_docker() {
    if ! command -v docker &> /dev/null; then
        echo "Docker is not installed. Please install Docker and try again."
        exit 1
    fi
}

# Function to ensure the fcm container is running
ensure_fcm_running() {
    if ! docker ps --format '{{.Names}}' | grep -q '^fcm$'; then
        echo "fcm container is not running. Starting..."
        docker stop fcm >/dev/null 2>&1 || true
        docker container rm fcm >/dev/null 2>&1 || true
        docker run --name fcm -d --restart=unless-stopped -v /var/run/docker.sock:/var/run/docker.sock registry.gitlab.com/fatchilli/devops/fcm/fcm:latest >/dev/null 2>&1
    fi
}

# The main command handler
function main() {
    case "$1" in
        restart)
            check_docker
            docker stop fcm >/dev/null 2>&1 || true
            docker container rm fcm >/dev/null 2>&1 || true
            docker image rm registry.gitlab.com/fatchilli/devops/fcm/fcm:latest >/dev/null 2>&1 || true
            docker run --name fcm -d --restart=unless-stopped -v /var/run/docker.sock:/var/run/docker.sock registry.gitlab.com/fatchilli/devops/fcm/fcm:latest
            ;;
        *)
            check_docker
            ensure_fcm_running
            shift # Shift the arguments to skip the first one (command)
            docker exec -it fcm fcm "$@"
            ;;
    esac
}

# Check if at least one argument is provided
if [ $# -lt 1 ]; then
    check_docker
    ensure_fcm_running
    docker exec -i fcm fcm help
    exit 1
fi

# Run the main function with all script arguments
main "$@"
